# .github/workflows/deploy.yml
name: Deploy to Production (NPM)

on:
  workflow_dispatch:  # Manually triggered
    inputs:
      reason:
        description: 'Why are you deploying?'
        required: false
        default: 'Manual trigger'

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install --save-dev typescript
          npm install --save-dev @types/node
          npm ci

      - name: Deploy to production
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Deploying application..."
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm publish
          rm ~/.npmrc
          echo "Done"
